### ISSUE TITLE
graph.py - y center

### ISSUE THREAD

**Issue by harirajeev** [Academic-Hammer/SciTSR#10]
In graph.py

def get_features(self):
    return {
      "x1": self.chunk.x1,
      "x2": self.chunk.x2,
      "y1": self.chunk.y1,
      "y2": self.chunk.y2,
      "x center": (self.chunk.x1 + self.chunk.x2) / 2,
      "y center": (self.chunk.y2 + self.chunk.y2) / 2,
      "relative x1": self.chunk.x1 / self.tab_w,
      "relative x2": self.chunk.x2 / self.tab_w,
      "relative y1": self.chunk.y1 / self.tab_h,
      "relative y2": self.chunk.y2  / self.tab_h,
      "relative x center": (self.chunk.x1 + self.chunk.x2) / 2 / self.tab_w,
      "relative y center": (self.chunk.y2 + self.chunk.y2) / 2 / self.tab_h,
      "height of chunk": self.chunk.y2 - self.chunk.y1,
      "width of chunk": self.chunk.x2 - self.chunk.x1
    }

Please refer to " "y center": (self.chunk.y2 + self.chunk.y2) / 2,"

Is this not **self.chuck.y1** + self.chunk.y2) / 2

thanks

**Comment by CZWin32768** [comment]
It should be `(self.chuck.y1 + self.chunk.y2) / 2`. 

Thanks! 👍
