### ISSUE TITLE
Can you get cell coordinates from the dataset?

### ISSUE THREAD

**Issue by curiousily** [Academic-Hammer/SciTSR#11]
I read through this [issue](https://github.com/Academic-Hammer/SciTSR/issues/1). Are chunk positions/coordinates the same as cell coordinates?

Thanks for open sourcing your work! 🎉

**Comment by CZWin32768** [comment]
There are different.

Chunk positions are the chunk locations on PDFs, which are produced by the pre-processing tool.

Cell coordinates represent the cell locations in tables. Just imagine the table lies on a grid.

An example for cell coordinates:

![image](https://user-images.githubusercontent.com/12969670/76312692-8af18f00-630e-11ea-95a7-4d2795caef03.png)

**Comment by curiousily** [comment]
Thank you!
