### ISSUE TITLE
question about vertex-to-edge graph

### ISSUE THREAD

**Issue by zjuPeco** [Academic-Hammer/SciTSR#3]
In your paper, you said

> To support edge features, the original graph is converted to a bipartite graph with additional nodes that represent edges in the original graph. With this setting, we use N edge-to-vertex graph attention blocks and N vertex-to-edge graph attention blocks to encode vertices and edges separately.

So the vertex-to-edge graph has two independent sets which are vertexes(V) and edges(E) respectively. But every "e" in E only has two connected "v"s in V, which means, in the vertext-to-edge attention block, every "query" only has two "key"s to match to get the attention value. 

Do I understand this right?

**Comment by CZWin32768** [comment]
It is right.

**Comment by zjuPeco** [comment]
thanks~
